### ISSUE TITLE
Tweak out of scope

### ISSUE THREAD

**Issue by dlongley** [iherman/ld-signatures-charter#9]
For avoidance of doubt, I think this:

> Definition of new signature or encryption functions. This Working Group will only define suitable terms to identify such functions that the community has developed, or will develop in future.

Should be changed to something like this:

> Definition of new cryptographic signature or encryption primitives. This Working Group will only define suitable terms to identify such primitives or their combinations that the community has developed, or will develop in future.

These changes would avoid leading people to believe that we can't define how to serialize the data to be signed, e.g., we should be able to say that the way you produce the data to be signed for LD Signature type Foo is:

1. Canonize content graph CG and hash it with hash function X.
2. Canonize proof graph PG and hash it with hash function X.
3. Concatenate the result from 1 and 2 (1 + 2).
4. Hash the result from 3 and sign it with signature function Y.

What is definitely out of scope is defining new cryptographic primitives, i.e., the WG will not be coming up with new elliptic curves  or defining new lattice-based cryptosystems.

**Comment by msporny** [comment]
@dlongley done in https://github.com/iherman/ld-signatures-charter/pull/11/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R289-R293 -- does that address your concerns?

**Comment by dlongley** [comment]
@msporny, yes, thanks.

**Comment by iherman** [comment]
#11 merged, closing.
